#!/bin/sh

set -e

TDIR=`mktemp -d`

if [ $# -ne 2 ]; then
	echo "Usage: hymn-key-pack [name] [path/to/key]"
	exit 1
fi

if [ ! -f $2 ]; then
	echo "key $2 does not exist, or is not a file"
	exit 1
fi

echo "creating nyfe key wrapper first"
nyfe keygen $TDIR/$1-wrapper.key

echo "encrypting $2 with wrapper"
nyfe encrypt -f $TDIR/$1-wrapper.key $2 $TDIR/$1.key

CURDIR=`pwd`

cd $TDIR && tar cf $CURDIR/$1.tar .
cd $CURDIR

rm -rf $TDIR

echo "key bundle $1.tar created"
tar tf $1.tar
