.nh
.ad 1
.TH SANCTUM 1
.SH NAME
sanctum \- A small, reviewable and capable VPN daemon.
.SH SYNOPSIS
.B sanctum
[\-c file] [\-d] [\-h] [\-v]
.SH DESCRIPTION
.I Sanctum
is a small, reviewable, capable, PQ-secure and fully privilege
separated VPN daemon.

.SH OPTIONS
.TP
.BR \-d
Run
.I sanctum
as a daemon. This option allows the program to run in the background,
detaching from the terminal.
.TP
.BR \-c " " file
Loads the given configuration file. See
.BR sanctum.conf(5).
.TP
.BR \-h
Prints the help. Display this help message and exit.
.TP
.BR \-v
Display version information. Show the version of the program and exit.

.SH DESIGN
.I Sanctum
is built using a multi-process approach where each process is only
doing one thing. This allows for more fine-grained sandboxing
in relation to permissions or allowed system calls.

Packets flow between these processes in a well-defined manner making
it impossible to move a packet straight from the red side to the black
side without passing the encryption process and vice-versa.

.SH ENCRYPTION
Traffic is by default encrypted under AES256-GCM with unique keys in
both the RX and TX directions using a 96-bit nonce consisting of a 32-bit
salt and 64-bit packet counter.

.I Sanctum
uses a strong symmetrical secret shared between two peers that wish to
communicate. Session keys are derived from the shared symmetrical secret
in combination with the shared secrets from a classical ECDH (x25519)
exchange and a PQ-secure ML-KEM-1024 exchange that happens in both RX
and TX directions.

Key exchanges are protected using a different key derived from the
shared symmetrical secret.

Keys are automatically expired after a given number of packets
have been sent on them (1 << 34), or after a 1-hour period.

.SH AUTHORS

.I Sanctum
was designed and written by Joris Vink <joris@sanctorum.se> and
is licensed under the ISC license.

.SH "SEE ALSO"
.BR sanctum.conf(5),
.BR ambry(1),
.BR hymn(1)
