#
# This is an example sanctum configuration.
# See sanctum.conf(5) for more details.
#

#
# The instance name.
#
# This is used to set the process name on all systems.
# On linux this is used as the interface name.
# On OpenBSD this name is set as the interface description.
#
instance laptop

#
# If we want to create a tap device, uncomment this.
# The default is a tun device.
#
#tap yes

#
# The path to the shared secret between peers. This shared secret
# is used to authenticate key exchanges and a derived key is included
# in the KDF in combination with the asymmetric x25519+mlkem-1024 parts.
#
secret /etc/sanctum/laptop.secret

#
# The ipv4 configuration of our interface.
#
tunnel 10.1.0.1/24 1422

#
# Additional routes over the tunnel can be added, sanctum will
# configure the system automatically.
#
# Note: The tunnel network is automatically routed.
#
#route 192.168.1.0/24

#
# Sanctum filters traffic and traffic not coming from known networks
# should be explicitly accepted. This is useful on gateways for example.
#
# Note: The tunnel network is automatically accepted.
#
#accept 0.0.0.0/0

#
# Set our local address to use. This can be left out in a client config
# for example as you want to bind to your current outgoing interface.
#
#local 1.2.3.4:8891

#
# The peer address we want to establish a tunnel towards.
# On the server side you can set this to 0.0.0.0/0 for unknown addresses.
#
peer 1.2.3.4:8891

#
# The control socket is used to obtain statistics via the `hymn` tool.
#
run control as user
control /tmp/sanctum-ctrl user

#
# The chapel process is responsible for the key exchanges.
#
run chapel as _chapel

#
# The bless and confess processes are the encryption/decryption
# processes and are mostly computational.
#
run bless as _bless
run confess as _confess

#
# The heaven-rx and heaven-tx processes are the "red" side of your
# tunnel and handle receiving and sending plaintext packets they
# receive from the tun/tap interface or confess.
#
run heaven-rx as _heaven-rx
run heaven-tx as _heaven-tx

#
# The purgatory-rx and purgatory-tx processes are the "black" side
# of your tunnel and handle receiving and sending encrypted packets
# they receive from the internet or bless.
#
run purgatory-rx as _purgatory-rx
run purgatory-tx as _purgatory-tx
