/*
 * Copyright (c) 2025 Joris Vink <joris@sanctorum.se>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

/*
 * Agelas encryption via the Nyfe library.
 *
 * The nonce here is still 96-bit much like in GCM mode, consisting of
 * the negotiated salt and packet counter. It is stuffed in a single
 * block and run through Agelas before the traffic is handled, this
 * forces the keystream generated by Agelas to be nonce dependent,
 * preventing a certain type of issue.
 */

#include <sys/types.h>

#include <stdio.h>

#include "sanctum.h"
#include "libnyfe.h"

/* Size of key input for Agelas. */
#define AGELAS_KEY_BYTES		64

/* Absorb rate for Agelas. */
#define AGELAS_ABSORB_RATE		136

/* Label for the kdf. */
#define AGELAS_KDF_LABEL		"SANCTUM.AGELAS.KDF"

/* The cipher indicator for -v. */
const char	*sanctum_cipher = "nyfe-agelas";

/*
 * The cipher context, we hold the key and one agelas context that
 * is re-initialized every encrypt/decrypt operation.
 */
struct cipher_agelas {
	struct nyfe_agelas		agelas;
	u_int8_t			key[AGELAS_KEY_BYTES];
};

/*
 * Perform any one-time cipher initialization.
 */
void
sanctum_cipher_init(void)
{
}

/*
 * Setup the cipher for use.
 */
void *
sanctum_cipher_setup(struct sanctum_key *key)
{
	struct nyfe_kmac256	kdf;
	struct cipher_agelas	*cipher;

	PRECOND(key != NULL);

	if ((cipher = calloc(1, sizeof(*cipher))) == NULL)
		fatal("failed to allocate cipher context");

	nyfe_zeroize_register(&kdf, sizeof(kdf));
	nyfe_zeroize_register(cipher, sizeof(*cipher));

	nyfe_kmac256_init(&kdf, key->key, sizeof(key->key),
	    AGELAS_KDF_LABEL, sizeof(AGELAS_KDF_LABEL) - 1);
	nyfe_kmac256_final(&kdf, cipher->key, sizeof(cipher->key));

	nyfe_zeroize(&kdf, sizeof(kdf));

	return (cipher);
}

/*
 * Encrypt and authenticate some data in combination with the given nonce
 * aad, etc.
 */
void
sanctum_cipher_encrypt(struct sanctum_cipher *cipher)
{
	struct cipher_agelas		*ctx;
	u_int8_t			block[AGELAS_ABSORB_RATE];

	PRECOND(cipher != NULL);

	VERIFY(cipher->pt != NULL);
	VERIFY(cipher->ct != NULL);
	VERIFY(cipher->tag != NULL);
	VERIFY(cipher->aad != NULL);
	VERIFY(cipher->nonce != NULL);
	VERIFY(cipher->nonce_len == SANCTUM_NONCE_LENGTH);

	ctx = cipher->ctx;

	nyfe_agelas_init(&ctx->agelas, ctx->key, sizeof(ctx->key));
	nyfe_agelas_aad(&ctx->agelas, cipher->aad, cipher->aad_len);

	/*
	 * Encrypt the nonce block once to move the keystream forward
	 * and make it depend on the nonce plaintext.
	 *
	 * We ignore the result of the encrypt operation.
	 */
	memset(block, 0, sizeof(block));
	memcpy(block, cipher->nonce, cipher->nonce_len);
	nyfe_agelas_encrypt(&ctx->agelas, block, block, sizeof(block));

	/* Now encrypt the plaintext and authenticate the entire thing. */
	nyfe_agelas_encrypt(&ctx->agelas,
	    cipher->pt, cipher->ct, cipher->data_len);
	nyfe_agelas_authenticate(&ctx->agelas, cipher->tag, SANCTUM_TAG_LENGTH);

	nyfe_mem_zero(block, sizeof(block));
	nyfe_mem_zero(&ctx->agelas, sizeof(ctx->agelas));
}

/*
 * Decrypt and authenticate some data in combination with the given nonce,
 * aad etc. Returns -1 if the data was unable to be authenticated.
 */
int
sanctum_cipher_decrypt(struct sanctum_cipher *cipher)
{
	struct cipher_agelas		*ctx;
	u_int8_t			tag[SANCTUM_TAG_LENGTH];
	u_int8_t			block[AGELAS_ABSORB_RATE];

	PRECOND(cipher != NULL);

	VERIFY(cipher->pt != NULL);
	VERIFY(cipher->ct != NULL);
	VERIFY(cipher->tag != NULL);
	VERIFY(cipher->aad != NULL);
	VERIFY(cipher->nonce != NULL);
	VERIFY(cipher->nonce_len == SANCTUM_NONCE_LENGTH);

	ctx = cipher->ctx;

	nyfe_agelas_init(&ctx->agelas, ctx->key, sizeof(ctx->key));
	nyfe_agelas_aad(&ctx->agelas, cipher->aad, cipher->aad_len);

	/*
	 * Encrypt the nonce block once to move the keystream forward
	 * and make it depend on the nonce plaintext.
	 *
	 * We ignore the result of the encrypt operation.
	 */
	memset(block, 0, sizeof(block));
	memcpy(block, cipher->nonce, cipher->nonce_len);
	nyfe_agelas_encrypt(&ctx->agelas, block, block, sizeof(block));

	/* Now encrypt the plaintext and authenticate the entire thing. */
	nyfe_agelas_decrypt(&ctx->agelas,
	    cipher->ct, cipher->pt, cipher->data_len);
	nyfe_agelas_authenticate(&ctx->agelas, tag, sizeof(tag));

	nyfe_mem_zero(block, sizeof(block));
	nyfe_mem_zero(&ctx->agelas, sizeof(ctx->agelas));

	if (nyfe_mem_cmp(cipher->tag, tag, sizeof(tag)))
		return (-1);

	return (0);
}

/*
 * Cleanup and wipe the cipher state.
 */
void
sanctum_cipher_cleanup(void *arg)
{
	struct cipher_agelas	*cipher;

	PRECOND(arg != NULL);

	cipher = arg;

	nyfe_zeroize(cipher, sizeof(*cipher));
	free(cipher);
}
