/*
 * Copyright (c) 2023 Joris Vink <joris@sanctorum.se>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

/*
 * Agelas via the Nyfe library.
 *
 * This is an experimental mode used to research the interaction between
 * a certain format of IPSec and the sponge based Agelas cipher.
 *
 * The nonce here is still 96-bit much like in GCM mode, consisting of
 * the negotiated salt and packet counter. It is stuffed in a single
 * block and run through Agelas before the traffic is handled, this
 * forces the keystream generated by Agelas to be nonce dependent,
 * preventing a certain type of issue.
 *
 * Oh yeah, you shouldn't use this.
 */

#include <sys/types.h>

#include <stdio.h>

#include "sanctum.h"
#include "libnyfe.h"

#define SANCTUM_DERIVE_LABEL	"SANCTUM.TRAFFIC.KDF"

#define NYFE_KEY_LEN		64
#define NYFE_TAG_LEN		32

/*
 * The local cipher state.
 */
struct cipher_agelas {
	struct nyfe_agelas	ctx;
	u_int8_t		key[NYFE_KEY_LEN];
};

/*
 * Setup the cipher.
 */
void *
sanctum_cipher_setup(struct sanctum_key *key)
{
	struct nyfe_kmac256	kdf;
	struct cipher_agelas	*cipher;

	PRECOND(key != NULL);

	if ((cipher = calloc(1, sizeof(*cipher))) == NULL)
		fatal("failed to allocate cipher context");

	nyfe_zeroize_register(&kdf, sizeof(kdf));
	nyfe_zeroize_register(cipher, sizeof(*cipher));

	nyfe_kmac256_init(&kdf, key->key, sizeof(key->key),
	    SANCTUM_DERIVE_LABEL, sizeof(SANCTUM_DERIVE_LABEL) - 1);
	nyfe_kmac256_final(&kdf, cipher->key, sizeof(cipher->key));

	nyfe_zeroize(&kdf, sizeof(kdf));

	return (cipher);
}

/*
 * Returns the overhead for This cipher. In this case it's the
 * 32 byte tag.
 */
size_t
sanctum_cipher_overhead(void)
{
	return (NYFE_TAG_LEN);
}

/*
 * Encrypt the packet data.
 * Automatically adds the integrity tag at the end of the ciphertext.
 */
void
sanctum_cipher_encrypt(void *arg, const void *nonce, size_t nonce_len,
    const void *aad, size_t aad_len, struct sanctum_packet *pkt)
{
	struct cipher_agelas	*cipher;
	u_int8_t		block[136];
	u_int8_t		*data, *tag;

	PRECOND(arg != NULL);
	PRECOND(nonce != NULL);
	PRECOND(aad != NULL);
	PRECOND(pkt != NULL);

	VERIFY(pkt->length + NYFE_TAG_LEN < sizeof(pkt->buf));
	VERIFY(nonce_len <= sizeof(block));

	cipher = arg;

	data = sanctum_packet_data(pkt);
	tag = data + pkt->length;

	memset(block, 0, sizeof(block));
	memcpy(block, nonce, nonce_len);

	nyfe_agelas_init(&cipher->ctx, cipher->key, sizeof(cipher->key));
	nyfe_agelas_aad(&cipher->ctx, aad, aad_len);

	nyfe_agelas_encrypt(&cipher->ctx, block, block, sizeof(block));
	nyfe_agelas_encrypt(&cipher->ctx, data, data, pkt->length);
	nyfe_agelas_authenticate(&cipher->ctx, tag, NYFE_TAG_LEN);

	sanctum_mem_zero(block, sizeof(block));
	sanctum_mem_zero(&cipher->ctx, sizeof(cipher->ctx));

	pkt->length += NYFE_TAG_LEN;
}

/*
 * Decrypt and verify a packet.
 */
int
sanctum_cipher_decrypt(void *arg, const void *nonce, size_t nonce_len,
    const void *aad, size_t aad_len, struct sanctum_packet *pkt)
{
	size_t			ctlen;
	struct cipher_agelas	*cipher;
	u_int8_t		block[136];
	u_int8_t		*data, *tag, calc[NYFE_TAG_LEN];

	PRECOND(arg != NULL);
	PRECOND(nonce != NULL);
	PRECOND(aad != NULL);
	PRECOND(pkt != NULL);

	VERIFY(pkt->length + NYFE_TAG_LEN < sizeof(pkt->buf));
	VERIFY(nonce_len <= sizeof(block));

	cipher = arg;

	data = sanctum_packet_data(pkt);
	tag = &pkt->buf[pkt->length - NYFE_TAG_LEN];
	ctlen = tag - data;

	memset(block, 0, sizeof(block));
	memcpy(block, nonce, nonce_len);

	nyfe_agelas_init(&cipher->ctx, cipher->key, sizeof(cipher->key));
	nyfe_agelas_aad(&cipher->ctx, aad, aad_len);

	nyfe_agelas_encrypt(&cipher->ctx, block, block, sizeof(block));
	nyfe_agelas_decrypt(&cipher->ctx, data, data, ctlen);
	nyfe_agelas_authenticate(&cipher->ctx, calc, sizeof(calc));

	sanctum_mem_zero(block, sizeof(block));
	sanctum_mem_zero(&cipher->ctx, sizeof(cipher->ctx));

	if (memcmp(tag, calc, sizeof(calc)))
		return (-1);

	return (0);
}

/*
 * Cleanup the cipher states.
 */
void
sanctum_cipher_cleanup(void *arg)
{
	struct cipher_agelas	*cipher;

	PRECOND(arg != NULL);

	cipher = arg;

	nyfe_zeroize(cipher, sizeof(*cipher));
	free(cipher);
}
